#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint

cd ./packages/restarfall
npm ci
npm run test
npm run build
cd ../..

cd ./packages/restarfall-react
npm ci
npm run test
npm run build
cd ../..

cd ./packages/restarfall-ext
npm ci
npm run test
npm run build
cd ../..
