#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm i
git add ./package-lock.json

cd ./packages/restarfall
npm i
git add ./package-lock.json
cd ../..

cd ./packages/restarfall-react
npm i
git add ./package-lock.json
cd ../..
