name: Publish  to npmjs
on: workflow_dispatch
jobs:
  restarfall-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
      - run: npm ci
      - run: npm run lint
  restarfall:
    needs: [restarfall-repo]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
      - name: Install root
        run: |
          npm ci
      - name: Test & build
        working-directory: ./packages/restarfall
        run: |
          npm ci
          npm run test
          npm run build
      - name: Publish
        working-directory: ./packages/restarfall
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  restarfall-react:
    needs: [restarfall]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
      - name: Install root
        run: |
          npm ci
      - name: Install & build restarfall
        working-directory: ./packages/restarfall
        run: |
          npm ci
          npm run build
      - name: Test & build
        working-directory: ./packages/restarfall-react
        run: |
          npm ci
          npm run test
          npm run build
      - name: Update depends
        run: npm run update-depends
      - name: Publish
        working-directory: ./packages/restarfall-react
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  restarfall-ext:
    needs: [restarfall]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
      - name: Install root
        run: |
          npm ci
      - name: Install & build restarfall
        working-directory: ./packages/restarfall
        run: |
          npm ci
          npm run build
      - name: Test & build
        working-directory: ./packages/restarfall-ext
        run: |
          npm ci
          npm run test
          npm run build
      - name: Update depends
        run: npm run update-depends
      - name: Publish
        working-directory: ./packages/restarfall-ext
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
